Repository kubescape/operator, pull requests merged in 2023-11, with the labels that each got.

#185 Update pr-merged.yaml
  .github/workflows/pr-merged.yaml
Labels: Bug fix

#174 feat(scan): deduplicate events sent to be processed
  config/config.go
  config/config_test.go
  continuousscanning/cooldownqueue.go
  continuousscanning/gvks.py
  continuousscanning/handlers.go
  continuousscanning/service.go
  continuousscanning/service_test.go
  go.mod
  go.sum
  main.go
  mainhandler/handlerequests.go
  utils/utils.go
Labels: enhancement

#186 Get namespace name from config
  mainhandler/imageregistryhandler.go
  mainhandler/imageregistryhandlerhelper.go
  mainhandler/vulnscan.go
Labels: release, Bug fix

#187 feat(continuousscan): don't trigger host scanner
  continuousscanning/handlers.go
  continuousscanning/service_test.go
Labels: enhancement, release

#190 Service discovery v2
  config/config.go
  go.mod
  go.sum
Labels: enhancement, release

#192 Error handling, restored commented-out code
  continuousscanning/handlers.go
  continuousscanning/service.go
  continuousscanning/service_test.go
  mainhandler/imageregistryhandlerhelper.go
  watcher/watcher.go
Labels: release, bug_fix

#177 Create scorecard.yml
  .github/workflows/scorecard.yml
  README.md
Labels: enhancement

#193 disable vulnerability manifests deletes
  watcher/watcher.go
Labels: release, bug_fix
