Repository kubescape/operator, pull requests merged in 2023-09, with the labels that each got.

#168 fix running without serviceDiscovery
  README.md
  config/config.go
  continuousscanning/service_test.go
  go.mod
  go.sum
  main.go
  mainhandler/handlerequests.go
  mainhandler/imageregistryhandler.go
  mainhandler/kubescapehandler.go
  mainhandler/vulnscan.go
  restapihandler/restapi.go
  restapihandler/triggeraction.go
Labels: enhancement, release

#170 Fix system-tests
  config/config.go
  config/config_test.go
  configuration/capabilities.json
  go.mod
  go.sum
  main.go
  mainhandler/handlecommandresponse.go
  mainhandler/imageregistryhandler.go
  mainhandler/kubescapehandler.go
Labels: release, Refactoring, Bug fix

#171 don't check for accountID without service discovery
  config/config.go
  config/config_test.go
  main.go
Labels: release, Refactoring

#172 Refactor error handling in backend package
  go.mod
  go.sum
  mainhandler/handlerequests.go
  mainhandler/handlerequestsutils.go
  mainhandler/imageregistryhandler.go
  mainhandler/kubescapehandler.go
  mainhandler/vulnscan.go
  restapihandler/triggeraction.go
  utils/types.go
  utils/typesutils.go
  watcher/watcher.go
Labels: release, Refactoring
