Repository kubescape/operator, pull requests merged in 2024-01, with the labels that each got.

#201 Trigger v0.1.70-hotfix release
  main.go
Labels: enhancement

#199 Adding pprof & fixed ListPods with fieldSelector
  go.mod
  go.sum
  main.go
  mainhandler/vulnscan.go
  watcher/watcher.go
Labels: enhancement

#205 Fix/instance
  go.mod
  go.sum
  mainhandler/getworkload.go
  mainhandler/getworkload_test.go
  mainhandler/handlerequests.go
  watcher/watcher.go
  watcher/watcher_test.go
Labels: release, Bug fix

#206 Fix/bump k8s interface
  .github/workflows/pr-merged.yaml
  go.mod
  go.sum
  watcher/watcher.go
  watcher/watcher_test.go
Labels: release
