Repository kubescape/operator, pull requests merged in 2024-03, with the labels that each got.

#212 send skipTLSVerify and Insecure in image scanning command
  go.mod
  mainhandler/imageregistryhandler.go
  mainhandler/testdata/vulnscan/registry-secret.json
  mainhandler/vulnscan.go
  mainhandler/vulnscan_test.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 3

#211 add daily report
  go.mod
  go.sum
  main.go
  mainhandler/handlerequests.go
  mainhandler/imageregistrycredentials.go
  mainhandler/imageregistryhandler.go
  mainhandler/imageregistryhandlerhelper.go
  mainhandler/kubescapehandler.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 3

#214 Update pr-merged.yaml
  .github/workflows/pr-merged.yaml
Labels: enhancement, Review effort [1-5]: 2

#215 bump actions/checkout to v4
  .github/workflows/scorecard.yml
Labels: enhancement, Review effort [1-5]: 1
